game_size: 9
num_history: 3
encoding_dim: 128
num_simulations: 10
c_puct: 1.
num_iters: 5
num_episodes: 5
batch_size: 16
nn_update_threshold: 0.55
nn_update_num_games: 10
log_dir: ./tmp/
lr: 0.01
momentum: 0.8
max_epochs: 50
