# game config
game_size: 7
num_history: 3

# trainer config
num_iters: 200
num_episodes: 50
compare_nn: false
nn_update_threshold: 0.55
nn_update_num_games: 40
temperature_threshold: 15
train_example_num_iters: 20
patience: 10
play_temperature: 1

# MCTS config
num_simulations: 50
c_puct: 1.

# NN trainer
log_dir: ./gomoku_logs/
lr: 0.001
momentum: 0.9
batch_size: 64
weight_decay: 0.0001
max_epochs: 15

# NN config
num_resnet_filters: 256
num_res_blocks: 8
value_head_hidden_dim: 256
