game_size: 9
num_history: 1
encoding_dim: 64
num_simulations: 25
c_puct: 1.
num_iters: 50
num_episodes: 100
batch_size: 16
nn_update_threshold: 0.50
nn_update_num_games: 100
log_dir: ./tmp/gomoku
lr: 0.01
max_epochs: 50
patience: 10
num_resnet_filters: 6
num_res_blocks: 8
value_head_hidden_dim: 64
