game_size: 3
num_history: 1
encoding_dim: 32
num_simulations: 25
c_puct: 1.
num_iters: 50
num_episodes: 100
batch_size: 32
nn_update_threshold: 0.50
nn_update_num_games: 100
log_dir: ./tmp/ttt/
lr: 0.01
max_epochs: 50
patience: 10

num_resnet_filters: 8
num_res_blocks: 3
value_head_hidden_dim: 16
