# game config
game_size: 3
num_history: 1

# trainer config
num_iters: 25
num_episodes: 25
compare_nn: false
nn_update_threshold: 0.55
nn_update_num_games: 50
temperature_threshold: 6
train_example_num_iters: 20
patience: 10
play_temperature: 1

# MCTS config
num_simulations: 25
c_puct: 1.

# NN trainer
log_dir: ./tictactoe_logs/
lr: 0.005
momentum: 0.8
batch_size: 64
weight_decay: 0.01
max_epochs: 10

# NN config
nn_arch: dual_resnet
num_resnet_filters: 256
num_res_blocks: 4
value_head_hidden_dim: 256
